import { Download, RotateCcw } from "lucide-react";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { EmptyState, LoadingState, MetricCard, ModelTypeBadge, Panel } from "../components/DashboardUI";
import { ChartDescription, CsvDownload, DemandTooltip, ModelLegendLabel, SeriesSwatch } from "../components/ChartUI";
import { ACTUAL_SERIES, compactDemandTick, formatInteger, formatMetric, METRIC_INFO, MODEL_COLORS, MODEL_ORDER, MODEL_SERIES, shortTime } from "../dashboardData";

const METRICS=["MAE","RMSE","MAPE","R2"];
function downloadCsv(models) { const headers=["rank","model_id","model","type","MAE_kW","RMSE_kW","MAPE_percent","R2","peak_MAE_kW","parameters","status"]; const ranked=[...models].filter(m=>m.metrics).sort((a,b)=>a.metrics.MAE-b.metrics.MAE); const rows=ranked.map((m,index)=>[index+1,m.model_id,m.display_name,m.probabilistic?"Probabilistic":"Deterministic",m.metrics.MAE,m.metrics.RMSE,m.metrics.MAPE,m.metrics.R2,m.metrics.peak_MAE,m.parameter_count,m.comparison_status]); const csv=[headers,...rows].map(row=>row.map(value=>`"${String(value??"").replaceAll('"','""')}"`).join(",")).join("\n"); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); const anchor=document.createElement("a"); anchor.href=url; anchor.download="model-comparison.csv"; anchor.click(); URL.revokeObjectURL(url); }
function MetricChart({ metric, models }) { const data=models.filter(m=>m.metrics).map(m=>({name:m.display_name.replace("Monte Carlo","MC"),value:m.metrics[metric],fill:MODEL_COLORS[m.model_id]})).sort((a,b)=>metric==="R2"?b.value-a.value:a.value-b.value); return <div className="small-chart"><h3>{METRIC_INFO[metric].label}</h3><ResponsiveContainer><BarChart data={data} layout="vertical" margin={{left:80,right:16,top:4,bottom:4}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" domain={metric==="R2"?["dataMin","auto"]:[0,"auto"]}/><YAxis type="category" dataKey="name" width={78} tick={{fontSize:10}}/><Tooltip formatter={value=>formatMetric(metric,value)}/><Bar dataKey="value" radius={[0,3,3,0]}/></BarChart></ResponsiveContainer></div>; }
export default function CompareModelsPage({ comparison, loading }) {
  const all=comparison?.models??[]; const defaultIds=[...all].filter(m=>m.metrics).sort((a,b)=>a.metrics.MAE-b.metrics.MAE).slice(0,3).map(m=>m.model_id); const [selected,setSelected]=useState(defaultIds); const [type,setType]=useState("all"); const [sort,setSort]=useState({key:"MAE",direction:"asc"});
  const ids=selected; const filtered=all.filter(m=>ids.includes(m.model_id)&&(type==="all"||(type==="prob")===m.probabilistic));
  const ranked=useMemo(()=>[...filtered].sort((a,b)=>{const av=sort.key==="name"?a.display_name:a.metrics?.[sort.key]; const bv=sort.key==="name"?b.display_name:b.metrics?.[sort.key]; if(av==null)return 1;if(bv==null)return -1;return (typeof av==="string"?av.localeCompare(bv):av-bv)*(sort.direction==="asc"?1:-1);}),[filtered,sort]);
  if(loading)return <LoadingState label="Recalculating aligned comparison metrics…"/>; if(!comparison)return <EmptyState title="Comparison evidence unavailable"/>;
  const available=all.filter(m=>m.metrics); const best=key=>[...available].sort((a,b)=>key==="R2"?b.metrics[key]-a.metrics[key]:a.metrics[key]-b.metrics[key])[0]; const sample=comparison.aligned_sample??[];
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const changeSort=key=>setSort(current=>({key,direction:current.key===key&&current.direction==="asc"?"desc":"asc"}));
  return <div className="page-stack"><header className="page-heading"><div><p className="eyebrow">Aligned test evidence</p><h1>Compare forecasting models</h1><p>Every reported metric is recalculated on the same {formatInteger(comparison.test_period.rows)} timestamp-aligned rows. Missing artifacts remain explicitly unavailable.</p></div><button type="button" className="button button--secondary" onClick={()=>downloadCsv(filtered)}><Download size={16} aria-hidden="true"/>Export metrics CSV</button></header>
    <Panel title="Comparison controls" eyebrow={`${comparison.test_period.start.slice(0,10)} to ${comparison.test_period.end.slice(0,10)}`}><div className="compare-controls"><div className="check-group" role="group" aria-label="Models"><button type="button" className="button button--quiet" onClick={()=>setSelected(selected.length?[]:MODEL_ORDER)}> {selected.length?"Clear selection":"Select all"}</button>{all.map(model=><label key={model.model_id} className="check"><input type="checkbox" name="comparison_models" checked={ids.includes(model.model_id)} onChange={()=>toggle(model.model_id)}/><SeriesSwatch modelId={model.model_id}/><span>{MODEL_SERIES[model.model_id]?.shortLabel??model.display_name}</span><span className="sr-only">{MODEL_SERIES[model.model_id]?.accessibleLabel}</span></label>)}</div><label className="field field--compact" htmlFor="model-type-filter"><span>Model type</span><select id="model-type-filter" name="model_type" autoComplete="off" value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option><option value="det">Deterministic</option><option value="prob">Probabilistic</option></select></label><button type="button" className="button button--secondary" onClick={()=>{setSelected(defaultIds);setType("all");setSort({key:"MAE",direction:"asc"});}}><RotateCcw size={16} aria-hidden="true"/>Reset</button></div><p className="chart-caption">The primary overlay displays at most three selected models. All seven remain available in aligned small multiples.</p></Panel>
    <section className="metric-grid"><MetricCard metric="MAE" value={best("MAE")?.metrics.MAE} detail={best("MAE")?.display_name}/><MetricCard metric="RMSE" value={best("RMSE")?.metrics.RMSE} detail={best("RMSE")?.display_name}/><MetricCard metric="MAPE" value={best("MAPE")?.metrics.MAPE} detail={best("MAPE")?.display_name}/><MetricCard metric="R2" value={best("R2")?.metrics.R2} detail={best("R2")?.display_name}/></section>
    <Panel title="Performance leaderboard" eyebrow="Sortable aligned metrics"><div className="table-scroll" tabIndex="0" aria-label="Scrollable model performance leaderboard"><table><caption className="sr-only">Seven-model leaderboard on the common aligned test period</caption><thead><tr><th>Rank</th><th aria-sort={sort.key==="name"?(sort.direction==="asc"?"ascending":"descending"):undefined}><button type="button" onClick={()=>changeSort("name")}>Model {sort.key==="name"?(sort.direction==="asc"?"↑":"↓"):""}</button></th><th>Type</th>{METRICS.map(metric=><th key={metric} aria-sort={sort.key===metric?(sort.direction==="asc"?"ascending":"descending"):undefined}><button type="button" onClick={()=>changeSort(metric)}>{metric} {sort.key===metric?(sort.direction==="asc"?"↑":"↓"):""}</button></th>)}<th>Peak MAE</th><th>Parameters</th><th>Inference</th><th>Status</th></tr></thead><tbody>{ranked.map((model,index)=><tr key={model.model_id}><td>{model.metrics?index+1:"—"}</td><td><ModelLegendLabel modelId={model.model_id} label={model.display_name}/></td><td><ModelTypeBadge probabilistic={model.probabilistic}/></td>{METRICS.map(metric=><td key={metric}>{model.metrics?formatMetric(metric,model.metrics[metric]):"—"}</td>)}<td>{model.metrics?formatMetric("MAE",model.metrics.peak_MAE):"—"}</td><td>{formatInteger(model.parameter_count)}</td><td>—</td><td><span className={`availability availability--${model.comparison_status}`}>{model.comparison_status}</span>{model.comparison_note&&<small className="cell-note">{model.comparison_note}</small>}</td></tr>)}</tbody></table></div></Panel>
    <Panel title="Metric profiles" eyebrow="Lower is better except R²"><div className="chart-grid">{METRICS.map(metric=><MetricChart key={metric} metric={metric} models={filtered}/>)}</div></Panel>
    <Panel title="Actual versus predicted demand" eyebrow={`${comparison.test_period.sampled_rows} evenly sampled aligned observations`}><ChartDescription id="comparison-overlay-description">Observed electricity demand compared with up to three selected forecasts on the same aligned test observations.</ChartDescription><div className="chart-frame chart-frame--large" role="img" aria-describedby="comparison-overlay-description"><ResponsiveContainer><LineChart data={sample} margin={{top:16,right:24,bottom:44,left:64}}><CartesianGrid vertical={false}/><XAxis dataKey="timestamp" tickFormatter={shortTime} minTickGap={42}/><YAxis tickFormatter={compactDemandTick} label={{value:"Demand (kW)",angle:-90,position:"insideLeft",className:"axis-label"}}/><Tooltip content={<DemandTooltip/>}/><Legend verticalAlign="top" align="left" height={44}/><Line dataKey="actual_kw" name="Actual" stroke={ACTUAL_SERIES.color} strokeWidth={2.75} dot={false} isAnimationActive={false}/>{filtered.filter(m=>m.metrics).slice(0,3).map(model=><Line key={model.model_id} dataKey={model.model_id} name={MODEL_SERIES[model.model_id]?.shortLabel??model.display_name} stroke={MODEL_COLORS[model.model_id]} strokeDasharray={MODEL_SERIES[model.model_id]?.dash} dot={false} strokeWidth={2} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div><div className="chart-footer"><p className="chart-caption">Actual is the fixed reference. Showing {Math.min(3,filtered.filter(model=>model.metrics).length)} selected model{Math.min(3,filtered.filter(model=>model.metrics).length)===1?"":"s"}; selection order determines inclusion when more than three are checked.</p><CsvDownload rows={sample} columns={["timestamp","actual_kw",...MODEL_ORDER]} filename="aligned-demand-comparison.csv"/></div></Panel>
    <Panel title="All-model aligned view" eyebrow="Seven small multiples · shared axes"><div className="small-multiples">{MODEL_ORDER.map(id=>{const model=all.find(item=>item.model_id===id);return <article className="small-multiple" key={id}><h3><ModelLegendLabel modelId={id} label={MODEL_SERIES[id].shortLabel}/></h3>{model?.metrics?<div className="chart-frame"><ResponsiveContainer><LineChart data={sample} margin={{top:8,right:12,bottom:28,left:44}}><CartesianGrid vertical={false}/><XAxis dataKey="timestamp" tickFormatter={shortTime} minTickGap={48}/><YAxis tickFormatter={compactDemandTick} width={40}/><Tooltip content={<DemandTooltip/>}/><Line dataKey="actual_kw" name="Actual" stroke={ACTUAL_SERIES.color} strokeOpacity={0.45} strokeWidth={1.5} dot={false} isAnimationActive={false}/><Line dataKey={id} name={MODEL_SERIES[id].shortLabel} stroke={MODEL_SERIES[id].color} strokeDasharray={MODEL_SERIES[id].dash} strokeWidth={2} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<EmptyState title="Model evidence unavailable" detail={model?.comparison_note??"No aligned prediction artifact is available."}/>}</article>})}</div></Panel>
    <div className="two-column"><Panel title="Peak versus normal error" eyebrow="MAE in kW"><div className="chart-frame"><ResponsiveContainer><BarChart data={filtered.filter(m=>m.metrics).map(m=>({name:MODEL_SERIES[m.model_id]?.shortLabel,peak:m.metrics.peak_MAE,normal:m.metrics.normal_demand_MAE}))} margin={{top:16,right:16,bottom:36,left:52}}><CartesianGrid vertical={false}/><XAxis dataKey="name" tick={false}/><YAxis tickFormatter={compactDemandTick} label={{value:"MAE (kW)",angle:-90,position:"insideLeft",className:"axis-label"}}/><Tooltip/><Legend/><Bar dataKey="normal" name="Normal demand" fill="#1F5A94"/><Bar dataKey="peak" name="Peak demand" fill="#7A5700"/></BarChart></ResponsiveContainer></div></Panel><Panel title="Error profile" eyebrow="MAE versus RMSE"><div className="chart-frame"><ResponsiveContainer><ScatterChart margin={{top:16,right:24,bottom:44,left:64}}><CartesianGrid/><XAxis type="number" dataKey="MAE" name="MAE" unit=" kW" label={{value:"MAE (kW)",position:"insideBottom",offset:-24,className:"axis-label"}}/><YAxis type="number" dataKey="RMSE" name="RMSE" unit=" kW" label={{value:"RMSE (kW)",angle:-90,position:"insideLeft",className:"axis-label"}}/><ZAxis range={[90,90]}/><Tooltip cursor={{strokeDasharray:"3 3"}} formatter={value=>`${Number(value).toFixed(2)} kW`}/>{filtered.filter(m=>m.metrics).map(model=><Scatter key={model.model_id} name={MODEL_SERIES[model.model_id]?.shortLabel} data={[{MAE:model.metrics.MAE,RMSE:model.metrics.RMSE,name:model.display_name}]} fill={MODEL_SERIES[model.model_id]?.color} shape={["circle","cross","triangle","diamond","square","star","wye"][MODEL_ORDER.indexOf(model.model_id)]} isAnimationActive={false}/>)}</ScatterChart></ResponsiveContainer></div><div className="chart-legend" aria-label="Error scatter model legend">{filtered.filter(m=>m.metrics).map(model=><ModelLegendLabel key={model.model_id} modelId={model.model_id}/>)}</div><p className="panel-note">Each model uses its permanent color and a distinct marker. Comparable inference latency was not recorded.</p></Panel></div>
    <Panel title="Statistical significance" eyebrow="Pairwise tests"><div className="table-scroll" tabIndex="0" aria-label="Scrollable pairwise statistical tests"><table><caption className="sr-only">Pairwise statistical significance tests for compared forecasting models</caption><thead><tr>{Object.keys(comparison.statistical_tests?.[0]??{}).map(key=><th key={key}>{key.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{comparison.statistical_tests.map((row,index)=><tr key={index}>{Object.values(row).map((value,i)=><td key={i}>{typeof value==="number"?value.toFixed(4):String(value)}</td>)}</tr>)}</tbody></table></div></Panel>
  </div>;
}
