import { Play } from "lucide-react";
import { Area, CartesianGrid, ComposedChart, Legend, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ChartDescription, CsvDownload, DemandTooltip } from "../components/ChartUI";
import { EmptyState, ErrorState, LoadingState, MetricCard, ModelSelector, ModelTypeBadge, Panel } from "../components/DashboardUI";
import { ACTUAL_SERIES, formatTimestamp, MODEL_SERIES, shortTime } from "../dashboardData";

const forecastDemandTick = value => new Intl.NumberFormat("en-GB", { maximumFractionDigits: 0 }).format(value);

export default function ForecastPage({ data }) {
  const models=data.registry?.models??[];
  const selected=models.find(model=>model.model_id===data.selectedModel);
  const rows=(data.forecast??[]).map(row=>({...row,label:shortTime(row.timestamp),interval:row.lower_95_kw!=null&&row.upper_95_kw!=null?[row.lower_95_kw,row.upper_95_kw]:null}));
  const demandValues=rows.flatMap(row=>[row.actual_kw,row.forecast_kw,row.lower_95_kw,row.upper_95_kw]).filter(Number.isFinite);
  const demandMin=demandValues.length?Math.min(...demandValues):0;
  const demandMax=demandValues.length?Math.max(...demandValues):1;
  const demandPadding=Math.max((demandMax-demandMin)*0.12,10);
  const yDomain=[Math.max(0,Math.floor((demandMin-demandPadding)/10)*10),Math.ceil((demandMax+demandPadding)/10)*10];
  const series=MODEL_SERIES[data.selectedModel];
  const descriptionId="forecast-chart-description";
  return <div className="page-stack">
    <header className="page-heading"><div><p className="eyebrow">Point and interval inference</p><h1>Generate a demand forecast</h1><p>Select a trained Keras model and a valid historical timestamp. The API builds its input window from preceding dataset rows.</p></div></header>
    <Panel title="Forecast controls" eyebrow="Configuration">
      <form className="control-grid" aria-describedby={data.errors.forecast?"forecast-error":undefined} onSubmit={event=>{event.preventDefault();if(!data.loading.forecast&&selected?.enabled)data.runForecast();}}><ModelSelector models={models} value={data.selectedModel} onChange={data.setSelectedModel}/><label className="field" htmlFor="forecast-timestamp"><span>Forecast from</span><input id="forecast-timestamp" name="forecast_timestamp" autoComplete="off" required type="datetime-local" value={data.selectedTimestamp} min={data.range?.valid_forecast_from?.slice(0,16)} max={data.range?.valid_forecast_to?.slice(0,16)} step="900" aria-describedby="forecast-timestamp-help" onChange={event=>data.setSelectedTimestamp(event.target.value)}/><small id="forecast-timestamp-help" className="field-help">Sri Lanka time · 15-minute intervals</small></label><label className="field" htmlFor="forecast-horizon"><span>Horizon</span><select id="forecast-horizon" name="forecast_horizon" autoComplete="off" value={data.forecastSteps} onChange={event=>data.setForecastSteps(Number(event.target.value))}><option value="12">3 hours · 12 intervals</option><option value="24">6 hours · 24 intervals</option><option value="48">12 hours · 48 intervals</option><option value="96">24 hours · 96 intervals</option></select></label><button type="submit" className="button button--primary run-button" disabled={data.loading.forecast||!selected?.enabled}><Play size={16} aria-hidden="true"/>{data.loading.forecast?"Running forecast…":"Run forecast"}</button></form>
      {selected&&<div className="model-context"><strong>{selected.display_name}</strong><ModelTypeBadge probabilistic={selected.probabilistic}/><span>{selected.lookback_steps} × 15-minute lookback</span><span>{selected.feature_count} features</span></div>}
    </Panel>
    <ErrorState id="forecast-error" message={data.errors.forecast} onRetry={data.runForecast}/>
    {data.forecastMeta&&!data.loading.forecast&&!data.errors.forecast?<p className="sr-only" role="status" aria-live="polite">Forecast complete. Results and downloadable chart data are available below.</p>:null}
    <Panel title="Forecast trace" eyebrow={data.forecastMeta?`${data.forecastMeta.steps} predicted intervals from ${formatTimestamp(data.forecastMeta.anchor_timestamp)}`:"Awaiting inference"} className="panel--chart">
      {data.loading.forecast?<LoadingState label="Running Keras inference…"/>:rows.length?<><ChartDescription id={descriptionId}>Observed electricity demand and the {series?.accessibleLabel}. The chart covers {data.forecastMeta?.steps} fifteen-minute forecast intervals. The demand axis is scaled to the visible data range and does not start at zero. {data.forecastMeta?.supports_intervals?"A backend-provided calibrated interval is shown.":"This is a point forecast; an interval is unavailable."}</ChartDescription><div className="chart-frame chart-frame--large" role="img" aria-describedby={descriptionId}><ResponsiveContainer><ComposedChart data={rows} margin={{top:16,right:24,bottom:44,left:72}}><CartesianGrid vertical={false}/><XAxis dataKey="label" minTickGap={36} tickLine/><YAxis domain={yDomain} tickFormatter={forecastDemandTick} tickLine label={{value:"Demand (kW)",angle:-90,position:"insideLeft",className:"axis-label"}}/><Tooltip content={<DemandTooltip forecastMeta={data.forecastMeta}/>}/><Legend verticalAlign="top" align="left" height={36}/>{data.forecastMeta?.supports_intervals&&<Area type="monotone" dataKey="interval" name="95% calibrated prediction interval" stroke={series?.color} strokeDasharray="3 3" strokeOpacity={0.45} fill={series?.color} fillOpacity={0.12} isAnimationActive={false}/>}<Line type="monotone" dataKey="actual_kw" name="Observed in forecast window" stroke={ACTUAL_SERIES.color} strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/><Line type="monotone" dataKey="forecast_kw" name={series?.shortLabel??"Forecast"} stroke={series?.color} strokeDasharray={series?.dash} strokeWidth={2.5} dot={rows.length<=48?{r:2}:false} connectNulls={false} isAnimationActive={false}/><ReferenceLine x={rows[0]?.label} stroke="#5F6F7E" strokeDasharray="5 4" label={{value:"Forecast starts",position:"insideTopRight",className:"prediction-start-label"}}/></ComposedChart></ResponsiveContainer></div><div className="chart-footer"><p className="chart-caption">Forecast starts {formatTimestamp(rows[0]?.timestamp)} · {data.forecastMeta?.steps} × 15 min · Y-axis scaled to visible demand · {data.forecastMeta?.supports_intervals?(data.forecastMeta.interval_note??"Backend-provided calibrated interval"):"Point forecast; interval unavailable"}</p><CsvDownload rows={data.forecast} columns={["timestamp","actual_kw","forecast_kw","lower_95_kw","upper_95_kw","mc_std_kw"]} filename="forecast-trace.csv"/></div></>:<EmptyState title="No forecast generated" detail="Choose a model and timestamp, then run the forecast. No synthetic preview data is shown."/>}
    </Panel>
    <section className="metric-grid metric-grid--three"><MetricCard label="Forecast points" value={data.forecastMeta?.steps??0} detail="15-minute intervals"/><MetricCard label="Interval method" value={data.forecastMeta?.supports_intervals?"Calibrated":"Point only"} detail={data.forecastMeta?.interval_note??"Run a forecast to inspect uncertainty"}/><MetricCard label="Actual comparison" value={data.forecastMeta?.comparison?.actuals_available??0} detail="Available within historical coverage"/></section>
  </div>;
}
